=== x-y-z/SteerSuite-CUDA/testcases/TestCaseSchema.xsd
<!-- 
  Copyright (c) 2009 Shawn Singh, Mubbasir Kapadia, Petros Faloutsos, Glenn Reinman
  See license.txt for complete license.

  This file defines the XML schema for SteerSuite test cases.  The main tags of the syntax are:
    - The root tag is <SteerBenchTestCase>.
    - <suggestedCameraView> - defines a camera view that represents a good look at the scenaro.
    - <agent> - defines the initial conditions of a single agent.
    - <agentRegion> - defines initial conditions of many agents at once, where agents are randomly located in a region.
    - <obstacle> - defines the initial conditions of an obstacle.
    - <obstacleRegion> - defines the initial conditions of many obstacles that are randomly located in a region.
-->

<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
            targetNamespace="http://www.magix.ucla.edu/steerbench" 
            xmlns:sb="http://www.magix.ucla.edu/steerbench"
            elementFormDefault="qualified">

  <!-- 
  Definitions of some "primitive" types:
   - Version is a fixed value.  Make sure your test cases have the same version number as this schema, or find the schema with the correct version number.
   - XYZTuple is used to describe points and vectors.
   - XYZTupleOrRandom is same as XYZTuple, with the additional possibility of it being specified as "random" instead of specific xyz values.
   - BoundingBox is for describing spatial min/max bounds in all 3 dimensions.
  -->
  <xsd:simpleType name="VersionType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="1.0"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="RandomFlagType">
    <xsd:restriction base="xsd:boolean">
      <xsd:pattern value="true"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:group name="XYZTupleElements">
    <xsd:sequence>
      <xsd:element name="x" type="xsd:float"/>
      <xsd:element name="y" type="xsd:float"/>
      <xsd:element name="z" type="xsd:float"/>
    </xsd:sequence>
  </xsd:group>

  <xsd:complexType name="XYZTupleType">
    <xsd:sequence>
      <xsd:group ref="sb:XYZTupleElements"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="XYZTupleOrRandomType">
    <xsd:choice>
      <xsd:element name="random" type="sb:RandomFlagType"/>
      <xsd:group ref="sb:XYZTupleElements"/>
    </xsd:choice>
  </xsd:complexType>

  <xsd:complexType name="BoundingBoxType">
    <xsd:sequence>
      <xsd:element name="xmin" type="xsd:float"/>
      <xsd:element name="xmax" type="xsd:float"/>
      <xsd:element name="ymin" type="xsd:float"/>
      <xsd:element name="ymax" type="xsd:float"/>
      <xsd:element name="zmin" type="xsd:float"/>
      <xsd:element name="zmax" type="xsd:float"/>
    </xsd:sequence>
  </xsd:complexType>

  <!--
  Definitions of the various Goal types.
  - GoalTypes describe a task that an agent should try to complete
  - GoalChoices is the group of all GoalTypes
  - GoalSequence is simply a ordered sequence of GoalChoices.
  In this way, any number of any goals can be specified.
  -->
  <xsd:complexType name="GoalTypeSeekStaticTarget">
    <xsd:all>
      <xsd:element name="targetLocation" type="sb:XYZTupleOrRandomType"/>
      <xsd:element name="desiredSpeed" type="xsd:float"/>
      <xsd:element name="timeDuration" type="xsd:float"/>
    </xsd:all>
  </xsd:complexType>

  <xsd:complexType name="GoalTypeFleeStaticTarget">
    <xsd:all>
      <xsd:element name="targetLocation" type="sb:XYZTupleOrRandomType"/>
      <xsd:element name="desiredSpeed" type="xsd:float"/>
      <xsd:element name="timeDuration" type="xsd:float"/>
    </xsd:all>
  </xsd:complexType>

  <xsd:complexType name="GoalTypeSeekDynamicTarget">
    <xsd:all>
      <xsd:element name="targetName" type="xsd:string"/>
      <xsd:element name="random" type="xsd:boolean"/>
      <xsd:element name="desiredSpeed" type="xsd:float"/>
      <xsd:element name="timeDuration" type="xsd:float"/>
    </xsd:all>
  </xsd:complexType>

  <xsd:complexType name="GoalTypeFleeDynamicTarget">
    <xsd:all>
      <xsd:element name="targetName" type="xsd:string"/>
      <xsd:element name="random" type="xsd:boolean"/>
      <xsd:element name="desiredSpeed" type="xsd:float"/>
      <xsd:element name="timeDuration" type="xsd:float"/>
    </xsd:all>
  </xsd:complexType>

  <xsd:complexType name="GoalTypeFlowStaticDirection">
    <xsd:all>
      <xsd:element name="targetDirection" type="sb:XYZTupleOrRandomType"/>
      <xsd:element name="desiredSpeed" type="xsd:float"/>
      <xsd:element name="timeDuration" type="xsd:float"/>
    </xsd:all>
  </xsd:complexType>

  <xsd:complexType name="GoalTypeFlowDynamicDirection">
    <xsd:all>
      <xsd:element name="type">
        <xsd:simpleType>
          <xsd:restriction base="xsd:string">
            <xsd:enumeration value="FOLLOW_CROWD"/>
            <xsd:enumeration value="BOIDS"/>
            <xsd:enumeration value="ADVECT"/>
            <xsd:enumeration value="OTHER"/>
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:element>
      <xsd:element name="desiredSpeed" type="xsd:float"/>
      <xsd:element name="timeDuration" type="xsd:float"/>
    </xsd:all>
  </xsd:complexType>

  <xsd:complexType name="GoalTypeIdle">
    <xsd:all>
      <xsd:element name="desiredSpeed" type="xsd:float"/>
      <xsd:element name="timeDuration" type="xsd:float"/>
    </xsd:all>
  </xsd:complexType>

  <xsd:group name="GoalChoices">
    <xsd:choice>
      <xsd:element name="seekStaticTarget" type="sb:GoalTypeSeekStaticTarget"/>
      <xsd:element name="fleeStaticTarget" type="sb:GoalTypeFleeStaticTarget"/>
      <xsd:element name="seekDynamicTarget" type="sb:GoalTypeSeekDynamicTarget"/>
      <xsd:element name="fleeDynamicTarget" type="sb:GoalTypeFleeDynamicTarget"/>
      <xsd:element name="flowStaticDirection" type="sb:GoalTypeFlowStaticDirection"/>
      <xsd:element name="flowDynamicDirection" type="sb:GoalTypeFlowDynamicDirection"/>
      <xsd:element name="idle" type="sb:GoalTypeIdle"/>
    </xsd:choice>
  </xsd:group>
  
  <xsd:complexType name="GoalSequenceType">
    <xsd:sequence>
      <xsd:group ref="sb:GoalChoices" minOccurs="1" maxOccurs="unbounded"/>
    </xsd:sequence>  
  </xsd:complexType>



  <!-- 
  Definitions for intermediate data structures.
  -->
  <xsd:complexType name="AgentInitialConditionsType">
    <xsd:all>
      <xsd:element name="position" type="sb:XYZTupleOrRandomType"/>
      <xsd:element name="direction" type="sb:XYZTupleOrRandomType"/>
      <xsd:element name="radius" type="xsd:float"/>
      <xsd:element name="speed" type="xsd:float"/>
    </xsd:all>
  </xsd:complexType>

  <xsd:complexType name="AgentRegionInitialConditionsType">
    <xsd:all>
      <xsd:element name="direction" type="sb:XYZTupleOrRandomType"/>
      <xsd:element name="radius" type="xsd:float"/>
      <xsd:element name="speed" type="xsd:float"/>
    </xsd:all>
  </xsd:complexType>

  
  
  <!-- 
  Definitions for the top-level data structures used to define the test case.
   - header contains global data of the test case
   - suggestedCameraView allows the test case to suggest to the user what camera views would be useful
   - agent specifies a single agent in the test case
   - agentRegion specifies a region of randomly-placed agents
   - obstacleRegion specifies a region of randomly-placed obstacles
   - NOTE: "obstacle", for now, is a simple bounding box, but may become a xsd:complexType in the future.
  -->
  <xsd:complexType name="HeaderType">
    <xsd:all>
      <xsd:element name="version" type="sb:VersionType"/>
      <xsd:element name="name" type="xsd:string"/>
      <xsd:element name="description" type="xsd:string" minOccurs="0"/>
      <xsd:element name="worldBounds" type="sb:BoundingBoxType"/>
      <xsd:element name="passingCriteria" type="xsd:string" minOccurs="0"/>
    </xsd:all>
  </xsd:complexType>

  <xsd:complexType name="SuggestedCameraViewType">
    <xsd:all>
      <xsd:element name="position" type="sb:XYZTupleType"/>
      <xsd:element name="lookat" type="sb:XYZTupleType"/>
      <xsd:element name="up" type="sb:XYZTupleType"/>
      <xsd:element name="fovy" type="xsd:float" minOccurs="0"/>
    </xsd:all>
  </xsd:complexType>

  <xsd:complexType name="AgentType">
    <xsd:all>
      <xsd:element name="name" type="xsd:string" minOccurs="0"/>
      <xsd:element name="initialConditions" type="sb:AgentInitialConditionsType"/>
      <xsd:element name="goalSequence" type="sb:GoalSequenceType"/>
    </xsd:all>
  </xsd:complexType>

  <xsd:complexType name="AgentRegionType">
    <xsd:all>
      <xsd:element name="numAgents" type="xsd:unsignedInt"/>
      <xsd:element name="regionBounds" type="sb:BoundingBoxType"/>
      <xsd:element name="initialConditions" type="sb:AgentRegionInitialConditionsType"/>
      <xsd:element name="goalSequence" type="sb:GoalSequenceType"/>
    </xsd:all>
  </xsd:complexType>

  <xsd:complexType name="ObstacleRegionType">
    <xsd:all>
      <xsd:element name="numObstacles" type="xsd:unsignedInt"/>
      <xsd:element name="regionBounds" type="sb:BoundingBoxType"/>
      <xsd:element name="obstacleSize" type="xsd:float"/>
      <xsd:element name="obstacleHeight" type="xsd:float"/>
    </xsd:all>
  </xsd:complexType>


  <!-- 
  Finally, describe the top level structure, and declare the root element.
  -->
  <xsd:group name="TopLevelChoices">
    <xsd:choice>
      <xsd:element name="suggestedCameraView" type="sb:SuggestedCameraViewType"/>
      <xsd:element name="agent" type="sb:AgentType"/>
      <xsd:element name="agentRegion" type="sb:AgentRegionType"/>
      <xsd:element name="obstacle" type="sb:BoundingBoxType"/>
      <xsd:element name="obstacleRegion" type="sb:ObstacleRegionType"/>
    </xsd:choice>
  </xsd:group>

  <xsd:complexType name="SteerBenchTestCaseType">
    <xsd:sequence>
      <xsd:element name="header" type="sb:HeaderType"/>
      <xsd:group ref="sb:TopLevelChoices" minOccurs="1" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:element name="SteerBenchTestCase" type="sb:SteerBenchTestCaseType"/>

</xsd:schema>

=== x-y-z/SteerSuite-CUDA/testcases/forest.xml
<!--
  Copyright (c) 2009 Shawn Singh, Mubbasir Kapadia, Petros Faloutsos, Glenn Reinman
  See license.txt for complete license.
-->

<SteerBenchTestCase xmlns="http://www.magix.ucla.edu/steerbench"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="http://www.magix.ucla.edu/steerbench 
                                        TestCaseSchema.xsd">

  <header>
    <version>1.0</version>
    <name>forest</name>
    <worldBounds>
      <xmin>-100</xmin>
      <xmax>100</xmax>
      <ymin>0</ymin>
      <ymax>0</ymax>
      <zmin>-100</zmin>
      <zmax>100</zmax>
    </worldBounds>
  </header>

  <suggestedCameraView>
    <position> <x>0</x> <y>150</y> <z>-30</z> </position>
    <lookat> <x>0</x> <y>0</y> <z>0</z> </lookat>
    <up> <x>0</x> <y>1</y> <z>0</z> </up>
    <fovy>45</fovy>
  </suggestedCameraView>

  <suggestedCameraView>
    <position> <x>44</x> <y>30</y> <z>0</z> </position>
    <lookat> <x>27</x> <y>0</y> <z>0</z> </lookat>
    <up> <x>0</x> <y>1</y> <z>0</z> </up>
    <fovy>45</fovy>
  </suggestedCameraView>

  <suggestedCameraView>
    <position> <x>0</x> <y>250</y> <z>-200</z> </position>
    <lookat> <x>0</x> <y>0</y> <z>0</z> </lookat>
    <up> <x>0</x> <y>1</y> <z>0</z> </up>
    <fovy>45</fovy>
  </suggestedCameraView>

  <obstacle>
    <xmin>-100</xmin>
    <xmax>-99</xmax>
    <ymin>0</ymin>
    <ymax>0</ymax>
    <zmin>-100</zmin>
    <zmax>100</zmax>
  </obstacle>

  <obstacle>
    <xmin>99.1</xmin>
    <xmax>100</xmax>
    <ymin>0</ymin>
    <ymax>0</ymax>
    <zmin>-100</zmin>
    <zmax>100</zmax>
  </obstacle>

  <obstacle>
    <xmin>-100</xmin>
    <xmax>100</xmax>
    <ymin>0</ymin>
    <ymax>0</ymax>
    <zmin>-100</zmin>
    <zmax>-99</zmax>
  </obstacle>

  <obstacle>
    <xmin>-100</xmin>
    <xmax>100</xmax>
    <ymin>0</ymin>
    <ymax>0</ymax>
    <zmin>99.1</zmin>
    <zmax>100</zmax>
  </obstacle>

  <obstacleRegion>
    <numObstacles>696</numObstacles>
    <regionBounds>
      <xmin>-100</xmin>
      <xmax>100</xmax>
      <ymin>0</ymin>
      <ymax>0</ymax>
      <zmin>-100</zmin>
      <zmax>100</zmax>
    </regionBounds>
    <obstacleSize>0.98</obstacleSize>
    <obstacleHeight>0.5</obstacleHeight>
  </obstacleRegion>

  
  <agentRegion>
    <numAgents>500</numAgents>
    <regionBounds>
      <xmin>-100</xmin>
      <xmax>100</xmax>
      <ymin>0</ymin>
      <ymax>0</ymax>
      <zmin>-100</zmin>
      <zmax>100</zmax>
    </regionBounds>
    <initialConditions>
      <direction> <random>true</random> </direction>
      <radius>0.5</radius>
      <speed>0</speed>
    </initialConditions>
    <goalSequence>
      <seekStaticTarget>
        <targetLocation> <random>true</random> </targetLocation>
        <desiredSpeed>1.3</desiredSpeed>
        <timeDuration>1000.0</timeDuration>
      </seekStaticTarget>
      <seekStaticTarget>
        <targetLocation> <random>true</random> </targetLocation>
        <desiredSpeed>1.3</desiredSpeed>
        <timeDuration>1000.0</timeDuration>
      </seekStaticTarget>
      <seekStaticTarget>
        <targetLocation> <random>true</random> </targetLocation>
        <desiredSpeed>1.3</desiredSpeed>
        <timeDuration>1000.0</timeDuration>
      </seekStaticTarget>
    </goalSequence>

  </agentRegion>

</SteerBenchTestCase>

=== x-y-z/SteerSuite-CUDA/testcases/simple-obstacle-2.xml
<!--
  Copyright (c) 2009 Shawn Singh, Mubbasir Kapadia, Petros Faloutsos, Glenn Reinman
  See license.txt for complete license.
-->

<SteerBenchTestCase xmlns="http://www.magix.ucla.edu/steerbench"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="http://www.magix.ucla.edu/steerbench 
                                        TestCaseSchema.xsd">

  <header>
    <version>1.0</version>
    <name>simple-obstacle-2</name>
    <worldBounds>
      <xmin>-100</xmin>
      <xmax>100</xmax>
      <ymin>0</ymin>
      <ymax>0</ymax>
      <zmin>-100</zmin>
      <zmax>100</zmax>
    </worldBounds>
  </header>

  <suggestedCameraView>
    <position> <x>0</x> <y>35</y> <z>-10</z> </position>
    <lookat> <x>0</x> <y>0</y> <z>0</z> </lookat>
    <up> <x>0</x> <y>1</y> <z>0</z> </up>
    <fovy>45</fovy>
  </suggestedCameraView>

  <obstacle>
    <xmin>-1.98</xmin>
    <xmax>-1</xmax>
    <ymin>0</ymin>
    <ymax>1</ymax>
    <zmin>-0.5</zmin>
    <zmax>0.5</zmax>
  </obstacle>

  <agent>
    <name>A</name>
    <initialConditions>
      <radius>0.5</radius>
      <position> <x>-0.7</x> <y>0</y> <z>-10</z> </position>
      <direction> <x>0</x> <y>0</y> <z>1</z> </direction>
      <speed>0</speed>
    </initialConditions>
    <goalSequence>
      <seekStaticTarget>
        <targetLocation> <x>0</x> <y>0</y> <z>10</z> </targetLocation>
        <desiredSpeed>1.3</desiredSpeed>
        <timeDuration>1000.0</timeDuration>
      </seekStaticTarget>
    </goalSequence>

  </agent>

</SteerBenchTestCase>

=== x-y-z/SteerSuite-CUDA/testcases/EXAMPLE.xml
<!--
  Copyright (c) 2009 Shawn Singh, Mubbasir Kapadia, Petros Faloutsos, Glenn Reinman
  See license.txt for complete license.
 
  This example test case is commented to describe (mostly) how to customize your own test 
  cases. Users are encouraged to create and share their own test cases.
  
  Test cases are XML using the "http://www.magix.ucla.edu/steerbench" namespace.  The schema
  for this namespace is provided in SteerSuite, in the file testcases/TestCaseSchema.xsd.  Be
  sure to validate your test case XML file against the schema to ensure there are no errors in
  the specification.

  To read test cases, use any standard XML parsing library (xerces, expat, tinyxml, etc.), or
  even easier, use the TestCaseReader C++ class provided in SteerLib.  The TestCaseReader class 
  hides all the XML parsing and test case initialization for you, and allows you to immediately 
  query the initial conditions for all agents, objects, and suggested camera views individually.
-->

<SteerBenchTestCase xmlns="http://www.magix.ucla.edu/steerbench"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="http://www.magix.ucla.edu/steerbench 
                                        TestCaseSchema.xsd">
  <!-- 
    The header tag must appear first.  Tags <description> and <passingCriteria> are optional. 
    For now, the passing criteria for each test case are documented as a human-readable strings.
    Eventually, <passingCriteria> will be turned into more detailed XML options for automation.
  -->
  <header>
    <version>1.0</version>
    <name>3-squeeze</name>
    <worldBounds>
      <xmin>-100</xmin>
      <xmax>100</xmax>
      <ymin>0</ymin>
      <ymax>0</ymax>
      <zmin>-100</zmin>
      <zmax>100</zmax>
    </worldBounds>
    <description>
      Users can add an optional description of your test case here.  It is often helpful
      to describe (in words) the goals that each agent has, and what types of 
      behaviors are being tested.
    </description>
    <passingCriteria> 
      Some example criteria:
      All agents must reach the goals within 10 seconds.
      All agents must have zero collisions that last longer than 0.1 seconds, using a threshold radius of 0.4.
      Agent A should not turn more than a total of 90 degrees.
    </passingCriteria>
  </header>

  <!-- 
    The user can specify zero or more "suggested camera views".  The vertical
    field-of-view tag, <fovy>, is optional.  The purpose of suggested camera views
    is to provide reasonable camera configurations that give a good view of the 
    action that will take place in the test case.  This data is purely information,
    and is not considered part of the "test case initial conditions".
  -->
  <suggestedCameraView>
    <position> <x>-10</x> <y>35</y> <z>-5</z> </position>
    <lookat> <x>0</x> <y>0</y> <z>0</z> </lookat>
    <up> <x>0</x> <y>1</y> <z>0</z> </up>
    <fovy>45</fovy>
  </suggestedCameraView>


  <!-- 
    The test case is specified by any number of <obstacle>, <obstacleRegion>, <agent>,
    and <agentRegion> tags.  Agents have several properties, and a sequence of goals.
    Each goal tag has slightly different information; see the TestCaseSchema.xsd schema
    to see all possible options for specifying goals.
  -->

  <!--
    Single obstacles are (for now) just axis-aligned static rectangular objects.
  -->  
  <obstacle>
    <xmin>-20</xmin>
    <xmax>20</xmax>
    <ymin>0</ymin>
    <ymax>1</ymax>
    <zmin>1.25</zmin>
    <zmax>3</zmax>
  </obstacle>

  <!-- 
    Obstacle regions can be used to specify a fixed number of randomly-placed obstacles.
    Currently, only square obstacles of the same size are supported;  It is possible
    that more options will be provided in the future.
  -->
  <obstacleRegion>
    <numObstacles>10</numObstacles>
    <obstacleSize>5.0</obstacleSize>
    <obstacleHeight>0.2</obstacleHeight>
    <regionBounds>
      <xmin>-40</xmin>
      <xmax>40</xmax>
      <ymin>0</ymin>
      <ymax>1</ymax>
      <zmin>-70</zmin>
      <zmax>70</zmax>
    </regionBounds>
  </obstacleRegion>
  
  <!-- 
    For agents, <name> is optional.

    The goalSequence tag accepts many different types of goals.  Only two
    typical goals are shown here.  The agent is expected to accomplish all 
    goals in the order they are listed, and to move on once they accomplish
    their goal or have been trying for <timeDuration>, whichever comes first.
    For a complete list of the types of goals and their options, see the 
    TestCaseSchema.xsd file that describes the syntax of the test case XML 
    document.
    
    <name> can be used to identify an agent when telling another agent to seek
    a dynamic target.
    
    Note that there are no units enforced in the test case; however we recommend
    using meters for distance units and seconds for time units.  In these units,
    1.3 m/s is actually a common typical walking speed for pedestrians, and 0.5 is
    a radius of an agent (slightly larger radius than the real physical bounds of
    an average human.)
  -->
  <agent>
    <name>Agent A</name>
    <initialConditions>
      <radius>0.5</radius>
      <position> <x>-10</x> <y>0</y> <z>-0.5</z> </position>
      <direction> <x>1</x> <y>0</y> <z>0</z> </direction>
      <speed>0</speed>
    </initialConditions>
    <goalSequence>
      <seekStaticTarget>
        <targetLocation> <x>10</x> <y>0</y> <z>-0.5</z> </targetLocation>
        <desiredSpeed>1.3</desiredSpeed>
        <timeDuration>1000.0</timeDuration>
      </seekStaticTarget>
      <fleeDynamicTarget>
        <targetName>Agent B</targetName>
        <random>false</random>
        <desiredSpeed>1.3</desiredSpeed>
        <timeDuration>1000.0</timeDuration>
      </fleeDynamicTarget>
    </goalSequence>

  </agent>

  <agent>
    <name>Agent B</name>
    <initialConditions>
      <radius>0.5</radius>
      <position> <random>true</random> </position>
      <direction> <x>1</x> <y>0</y> <z>0</z> </direction>
      <speed>0</speed>
    </initialConditions>
    <goalSequence>
      <seekDynamicTarget>
        <targetName>Setting random to true overrides any targetName here.</targetName>
        <random>true</random>
        <desiredSpeed>1.3</desiredSpeed>
        <timeDuration>1000.0</timeDuration>
      </seekDynamicTarget>
    </goalSequence>

  </agent>


  <!-- 
    Many randomly-placed agents can be defined in an <agentRegion> element.
    
    Any XML tag that expects an <x> <y> <z> tuple can be made random by replacing
    the <x>, <y>, <z> tags with the <random> tag.  In this example agent region, 
    all agents start off with a random direction.
  -->
  <agentRegion>
    <numAgents>30</numAgents>
    <regionBounds>
      <xmin>-100</xmin>
      <xmax>100</xmax>
      <ymin>0</ymin>
      <ymax>0</ymax>
      <zmin>-100</zmin>
      <zmax>100</zmax>
    </regionBounds>
    <initialConditions>
      <radius>0.5</radius>
      <direction> <random>true</random> </direction>
      <speed>0</speed>
    </initialConditions>
    <goalSequence>
      <idle>
        <desiredSpeed>1.3</desiredSpeed>
        <timeDuration>1000.0</timeDuration>
      </idle>
    </goalSequence>

  </agentRegion>
  
</SteerBenchTestCase>

=== x-y-z/SteerSuite-CUDA/testcases/double-squeeze.xml
<!--
  Copyright (c) 2009 Shawn Singh, Mubbasir Kapadia, Petros Faloutsos, Glenn Reinman
  See license.txt for complete license.
-->

<SteerBenchTestCase xmlns="http://www.magix.ucla.edu/steerbench"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="http://www.magix.ucla.edu/steerbench 
                                        TestCaseSchema.xsd">

  <header>
    <version>1.0</version>
    <name>double-squeeze</name>
    <worldBounds>
      <xmin>-100</xmin>
      <xmax>100</xmax>
      <ymin>0</ymin>
      <ymax>0</ymax>
      <zmin>-100</zmin>
      <zmax>100</zmax>
    </worldBounds>
  </header>

  <suggestedCameraView>
    <position> <x>-10</x> <y>35</y> <z>-5</z> </position>
    <lookat> <x>0</x> <y>0</y> <z>0</z> </lookat>
    <up> <x>0</x> <y>1</y> <z>0</z> </up>
    <fovy>45</fovy>
  </suggestedCameraView>

  <suggestedCameraView>
    <position> <x>-10</x> <y>35</y> <z>-0</z> </position>
    <lookat> <x>0</x> <y>0</y> <z>0</z> </lookat>
    <up> <x>0</x> <y>1</y> <z>0</z> </up>
    <fovy>45</fovy>
  </suggestedCameraView>

  <suggestedCameraView>
    <position> <x>0</x> <y>35</y> <z>-10</z> </position>
    <lookat> <x>0</x> <y>0</y> <z>0</z> </lookat>
    <up> <x>0</x> <y>1</y> <z>0</z> </up>
    <fovy>45</fovy>
  </suggestedCameraView>

  <obstacle>
    <xmin>-20</xmin>
    <xmax>20</xmax>
    <ymin>0</ymin>
    <ymax>1</ymax>
    <zmin>1.25</zmin>
    <zmax>3</zmax>
  </obstacle>

  <obstacle>
    <xmin>-20</xmin>
    <xmax>20</xmax>
    <ymin>0</ymin>
    <ymax>1</ymax>
    <zmin>-3</zmin>
    <zmax>-1.25</zmax>
  </obstacle>

  <agent>
    <name>A</name>
    <initialConditions>
      <radius>0.5</radius>
      <position> <x>-10</x> <y>0</y> <z>-0.5</z> </position>
      <direction> <x>1</x> <y>0</y> <z>0</z> </direction>
      <speed>0</speed>
    </initialConditions>
    <goalSequence>
      <seekStaticTarget>
        <targetLocation> <x>15</x> <y>0</y> <z>0</z> </targetLocation>
        <desiredSpeed>1.3</desiredSpeed>
        <timeDuration>1000.0</timeDuration>
      </seekStaticTarget>
    </goalSequence>

  </agent>

  <agent>
    <name>B</name>
    <initialConditions>
      <radius>0.5</radius>
      <position> <x>10</x> <y>0</y> <z>-0.5</z> </position>
      <direction> <x>-1</x> <y>0</y> <z>0</z> </direction>
      <speed>0</speed>
    </initialConditions>
    <goalSequence>
      <seekStaticTarget>
        <targetLocation> <x>-15</x> <y>0</y> <z>0</z> </targetLocation>
        <desiredSpeed>1.3</desiredSpeed>
        <timeDuration>1000.0</timeDuration>
      </seekStaticTarget>
    </goalSequence>

  </agent>

  <agent>
    <name>C</name>
    <initialConditions>
      <radius>0.5</radius>
      <position> <x>-10</x> <y>0</y> <z>0.5</z> </position>
      <direction> <x>1</x> <y>0</y> <z>0</z> </direction>
      <speed>0</speed>
    </initialConditions>
    <goalSequence>
      <seekStaticTarget>
        <targetLocation> <x>15</x> <y>0</y> <z>0</z> </targetLocation>
        <desiredSpeed>1.3</desiredSpeed>
        <timeDuration>1000.0</timeDuration>
      </seekStaticTarget>
    </goalSequence>

  </agent>

  <agent>
    <name>D</name>
    <initialConditions>
      <radius>0.5</radius>
      <position> <x>10</x> <y>0</y> <z>0.5</z> </position>
      <direction> <x>-1</x> <y>0</y> <z>0</z> </direction>
      <speed>0</speed>
    </initialConditions>
    <goalSequence>
      <seekStaticTarget>
        <targetLocation> <x>-15</x> <y>0</y> <z>0</z> </targetLocation>
        <desiredSpeed>1.3</desiredSpeed>
        <timeDuration>1000.0</timeDuration>
      </seekStaticTarget>
    </goalSequence>

  </agent>

</SteerBenchTestCase>

=== x-y-z/SteerSuite-CUDA/testcases/free-tickets.xml
<!--
  Copyright (c) 2009 Shawn Singh, Mubbasir Kapadia, Petros Faloutsos, Glenn Reinman
  See license.txt for complete license.
-->

<SteerBenchTestCase xmlns="http://www.magix.ucla.edu/steerbench"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="http://www.magix.ucla.edu/steerbench 
                                        TestCaseSchema.xsd">

  <header>
    <version>1.0</version>
    <name>free-tickets</name>
    <worldBounds>
      <xmin>-100</xmin>
      <xmax>100</xmax>
      <ymin>0</ymin>
      <ymax>0</ymax>
      <zmin>-100</zmin>
      <zmax>100</zmax>
    </worldBounds>
  </header>

  <suggestedCameraView>
    <position> <x>0</x> <y>250</y> <z>-200</z> </position>
    <lookat> <x>0</x> <y>0</y> <z>0</z> </lookat>
    <up> <x>0</x> <y>1</y> <z>0</z> </up>
    <fovy>45</fovy>
  </suggestedCameraView>

  <suggestedCameraView>
    <position> <x>0</x> <y>150</y> <z>-30</z> </position>
    <lookat> <x>0</x> <y>0</y> <z>0</z> </lookat>
    <up> <x>0</x> <y>1</y> <z>0</z> </up>
    <fovy>45</fovy>
  </suggestedCameraView>

  <suggestedCameraView>
    <position> <x>0</x> <y>10</y> <z>-10</z> </position>
    <lookat> <x>0</x> <y>0</y> <z>0</z> </lookat>
    <up> <x>0</x> <y>1</y> <z>0</z> </up>
    <fovy>45</fovy>
  </suggestedCameraView>

  <agentRegion>
    <numAgents>200</numAgents>
    <regionBounds>
      <xmin>-50</xmin>
      <xmax>50</xmax>
      <ymin>0</ymin>
      <ymax>0</ymax>
      <zmin>-50</zmin>
      <zmax>50</zmax>
    </regionBounds>
    <initialConditions>
      <direction> <random>true</random> </direction>
      <radius>0.5</radius>
      <speed>0</speed>
    </initialConditions>
    <goalSequence>
      <seekStaticTarget>
        <targetLocation> <x>0</x> <y>0</y> <z>0</z> </targetLocation>
        <desiredSpeed>1.3</desiredSpeed>
        <timeDuration>1000.0</timeDuration>
      </seekStaticTarget>
      <seekStaticTarget>
        <targetLocation> <random>true</random> </targetLocation>
        <desiredSpeed>1.3</desiredSpeed>
        <timeDuration>1000.0</timeDuration>
      </seekStaticTarget>
    </goalSequence>

  </agentRegion>

</SteerBenchTestCase>
